

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: chemtutor_db
      POSTGRES_USER: chemtutor_user
      POSTGRES_PASSWORD: chemtutor__password_100  
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chemtutor_user -d chemtutor_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    dns: ["8.8.8.8", "1.1.1.1"]
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DEBUG=1
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app   # 👈 ensures pytest can find 'api' and 'chemtutor'
      

volumes:
  db_data:
