services:
  - type: web
    name: chemtutor
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn chemtutor.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chemtutor_db
          property: connectionString
databases:
  - name: chemtutor_db
