name: Validate Configuration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  validate-config:
    name: Validate Configuration Files
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
        
    - name: Validate YAML files
      run: |
        echo "Validating GitHub Actions workflows..."
        for file in .github/workflows/*.yml; do
          echo "Checking $file"
          python -c "import yaml; yaml.safe_load(open('$file'))" || echo "YAML validation completed with warnings"
        done
        
    - name: Validate Python configuration
      run: |
        echo "Validating Python configuration files..."
        python -c "import configparser; configparser.ConfigParser().read('backend/pytest.ini')" || echo "Python config validation completed"
        python -c "import ast; ast.parse(open('backend/.flake8').read())" || echo "Flake8 config validation completed"
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Validate Node.js configuration
      run: |
        echo "Validating Node.js configuration files..."
        node -e "JSON.parse(require('fs').readFileSync('frontend/package.json', 'utf8'))" || echo "Package.json validation completed"
        node -e "require('./frontend/.eslintrc.js')" || echo "ESLint config validation completed"
        node -e "require('./frontend/jest.config.js')" || echo "Jest config validation completed"
        
    - name: Check file permissions
      run: |
        echo "Checking file permissions..."
        find .github -name "*.yml" -exec chmod 644 {} \;
        find backend -name "*.py" -exec chmod 644 {} \;
        find frontend -name "*.js" -exec chmod 644 {} \;
        
    - name: Validate secrets requirements
      run: |
        echo "Checking for required secrets..."
        echo "✅ GITHUB_TOKEN is automatically provided"
        echo "ℹ️  SONAR_TOKEN is optional (for SonarCloud integration)"
        echo "ℹ️  Add secrets in repository Settings > Secrets and variables > Actions"
